# netlify.toml
[build]
  command = "npx create-next-app@latest && npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "@netlify/plugin-emails"
